<?php

/**
 * This file is part of G.Snowhawk Framework.
 *
 * Copyright (c)2016 PlusFive (https://www.plus-5.com)
 *
 * This software is released under the MIT License.
 * https://www.plus-5.com/licenses/mit-license
 */

namespace Gsnowhawk\Common\Html;

/**
 * Methods for form management.
 *
 * @license  https://www.plus-5.com/licenses/mit-license  MIT License
 * @author   Taka Goto <www.plus-5.com>
 */
class Tags
{
    protected $metadata_contents = [
        'base' => 0, 'command' => 0, 'link' => 0, 'meta' => 0,
        'noscript' => 0, 'script' => 0, 'style' => 0, 'title' => 0,
    ];

    protected $flow_contents = [
        'a' => 0, 'abbr' => 0, 'address' => 0, 'area' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0,
        'b' => 0, 'bdi' => 0, 'bdo' => 0, 'blockquote' => 0, 'br' => 0, 'button' => 0,
        'canvas' => 0, 'cite' => 0, 'code' => 0, 'command' => 0,
        'datalist' => 0, 'del' => 0, 'details' => 0, 'dfn' => 0, 'div' => 0, 'dl' => 0,
        'em' => 0, 'embed' => 0, 'fieldset' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0,
        'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'hgroup' => 0, 'hr' => 0,
        'i' => 0, 'iframe' => 0, 'img' => 0, 'input' => 0, 'ins' => 0, 'kbd' => 0, 'keygen' => 0,
        'label' => 0, 'map' => 0, 'mark' => 0, 'math' => 0, 'menu' => 0, 'meter' => 0,
        'nav' => 0, 'noscript' => 0, 'object' => 0, 'ol' => 0, 'output' => 0,
        'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'ruby' => 0,
        's' => 0, 'samp' => 0, 'script' => 0, 'section' => 0, 'select' => 0, 'small' => 0, 'span' => 0,
        'strong' => 0, 'style' => 0, 'sub' => 0, 'sup' => 0, 'svg' => 0, 'table' => 0, 'textarea' => 0, 'time' => 0,
        'u' => 0, 'ul' => 0, 'var' => 0, 'video' => 0, 'wbr' => 0,
        'textnode' => 0,
    ];

    protected $sectioning_contents = [
        'article' => 0, 'aside' => 0, 'nav' => 0, 'section' => 0,
    ];

    protected $heading_contents = [
        'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'hgroup' => 0,
    ];

    protected $phrasing_contents = [
        'a' => 0, 'abbr' => 0, 'area' => 0, 'audio' => 0, 'b' => 0, 'bdi' => 0, 'bdo' => 0, 'br' => 0, 'button' => 0,
        'canvas' => 0, 'cite' => 0, 'code' => 0, 'command' => 0, 'datalist' => 0, 'del' => 0, 'dfn' => 0,
        'em' => 0, 'embed' => 0, 'i' => 0, 'iframe' => 0, 'img' => 0, 'input' => 0, 'ins' => 0,
        'kbd' => 0, 'keygen' => 0, 'label' => 0, 'map' => 0, 'mark' => 0, 'math' => 0, 'meter' => 0,
        'noscript' => 0, 'object' => 0, 'output' => 0, 'progress' => 0, 'q' => 0, 'ruby' => 0,
        's' => 0, 'samp' => 0, 'script' => 0, 'select' => 0, 'small' => 0, 'span' => 0, 'strong' => 0,
        'sub' => 0, 'sup' => 0, 'svg' => 0, 'textarea' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0, 'wbr' => 0,
        'textnode' => 0,
    ];

    protected $embedded_contents = [
        'audio' => 0, 'canvas' => 0, 'embed' => 0, 'iframe' => 0, 'img' => 0,
        'math' => 0, 'object' => 0, 'svg' => 0, 'video' => 0,
    ];

    protected $interactive_contents = [
        'a' => 0, 'audio' => 0, 'button' => 0, 'details' => 0, 'embed' => 0,
        'iframe' => 0, 'img' => 0, 'input' => 0, 'keygen' => 0, 'label' => 0,
        'menu' => 0, 'object' => 0, 'select' => 0, 'textarea' => 0, 'video' => 0,
    ];

    protected $transparents = [
        'a' => 0, 'audio' => 0, 'canvas' => 0, 'del' => 0, 'ins' => 0,
        'map' => 0, 'noscript' => 0, 'object' => 0, 'video' => 0,
    ];

    protected $all_tags = [
        'html' => 0,
        'head' => 0, 'title' => 0, 'base' => 0, 'link' => 0, 'meta' => 0, 'style' => 0,
        'body' => 0, 'article' => 0, 'section' => 0, 'nav' => 0, 'aside' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'footer' => 0, 'address' => 0, 'hgroup' => 0,
        'p' => 0, 'hr' => 0, 'pre' => 0, 'blockquote' => 0, 'ol' => 0, 'ul' => 0, 'li' => 0, 'dl' => 0, 'dt' => 0, 'dd' => 0, 'figure' => 0, 'figcaption' => 0, 'div' => 0, 'main' => 0,
        'a' => 0, 'em' => 0, 'strong' => 0, 'small' => 0, 's' => 0, 'cite' => 0, 'q' => 0, 'dfn' => 0, 'abbr' => 0, 'data' => 0, 'time' => 0, 'code' => 0, 'var' => 0, 'samp' => 0, 'kbd' => 0, 'sub' => 0, 'sup' => 0, 'i' => 0, 'b' => 0, 'u' => 0, 'mark' => 0, 'ruby' => 0, 'rb' => 0, 'rt' => 0, 'rtc' => 0, 'rp' => 0, 'bdi' => 0, 'bdo' => 0, 'span' => 0, 'br' => 0, 'wbr' => 0,
        'ins' => 0, 'del' => 0,
        'img' => 0, 'iframe' => 0, 'embed' => 0, 'object' => 0, 'param' => 0, 'video' => 0, 'audio' => 0, 'source' => 0, 'track' => 0, 'map' => 0, 'area' => 0,
        'table' => 0, 'caption' => 0, 'colgroup' => 0, 'col' => 0, 'tbody' => 0, 'thead' => 0, 'tfoot' => 0, 'tr' => 0, 'td' => 0, 'th' => 0,
        'form' => 0, 'label' => 0, 'input' => 0, 'button' => 0, 'select' => 0, 'datalist' => 0, 'optgroup' => 0, 'option' => 0, 'textarea' => 0, 'keygen' => 0, 'output' => 0, 'progress' => 0, 'meter' => 0, 'fieldset' => 0, 'legend' => 0,
        'script' => 0, 'noscript' => 0, 'template' => 0, 'canvas' => 0,
    ];

    protected $empty_tags = [
        'area' => 0, 'base' => 0, 'br' => 0, 'col' => 0, 'command' => 0, 'embed' => 0,
        'hr' => 0, 'img' => 0, 'input' => 0, 'keygen' => 0, 'link' => 0, 'meta' => 0,
        'param' => 0, 'source' => 0, 'track' => 0, 'wbr' => 0,
    ];

    protected $omit_start_tags = [
        'html' => 0, 'head' => 0, 'body' => 0, 'colgroup' => 0, 'tbody' => 0,
    ];

    protected $omit_end_tags = [
        'html' => 0, 'head' => 0, 'body' => 0, 'colgroup' => 0, 'tbody' => 0,
        'li' => 0, 'dt' => 0, 'dd' => 0, 'p' => 0, 'rt' => 0, 'rp' => 0, 'optgroup' => 0, 'option' => 0,
        'thead' => 0, 'tfoot' => 0, 'tr' => 0, 'td' => 0, 'th' => 0,
    ];

    protected $inline_tags = [
        'a' => 0,
        'em' => 0, 'strong' => 0, 'i' => 0, 'b' => 0, 'u' => 0,
        'mark' => 0, 'small' => 0, 's' => 0, 'cite' => 0,
        'q' => 0, 'dfn' => 0, 'abbr' => 0, 'data' => 0, 'time' => 0,
        'code' => 0, 'var' => 0, 'samp' => 0, 'kbd' => 0,
        'sub' => 0, 'sup' => 0,
        'ruby' => 0, 'rb' => 0, 'rt' => 0, 'rtc' => 0, 'rp' => 0,
        'bdi' => 0, 'bdo' => 0, 'span' => 0,
        'br' => 0, 'wbr' => 0,
    ];

    protected $preformatted_tags = ['pre' => 0, 'textarea' => 0];

    protected $strange_tags = ['a' => 0, 'del' => 0, 'ins' => 0];

    protected $always_indention_right = ['br' => 0];

    protected $never_indention_end = [
        'title' => 0,
        'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0,
        'li' => 0, 'dt' => 0, 'dd' => 0, 'p' => 0, 'rt' => 0, 'rp' => 0, 'option' => 0,
        'caption' => 0, 'td' => 0, 'th' => 0,
        'button' => 0,
    ];

    protected $never_indention_start_left = ['br' => 0];

    protected $never_indention_start_right = [
        'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0,
        'li' => 0, 'dt' => 0, 'dd' => 0, 'p' => 0, 'rt' => 0, 'rp' => 0, 'option' => 0,
        'caption' => 0, 'td' => 0, 'th' => 0,
    ];

    protected $valid_parents = [
        'head' => ['html' => 0],
        'title' => ['head' => 0, 'template' => 0],
        'base' => ['head' => 0, 'template' => 0],
        'link' => ['head' => 0, 'noscript' => 0, 'template' => 0],
        'meta' => ['head' => 0, 'noscript' => 0, 'template' => 0],
        'style' => ['head' => 0, 'noscript' => 0, 'template' => 0],
        'body' => ['html' => 0],
        'article' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'section' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'nav' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'aside' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'h1' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'h2' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'h3' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'h4' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'h5' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'h6' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'header' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'form' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'footer' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'form' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'video' => 0],
        'address' => ['a' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'p' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'hr' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'pre' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'blockquote' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'ol' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'ul' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'li' => ['ol' => 0, 'template' => 0, 'ul' => 0],
        'dl' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'dt' => ['dl' => 0, 'template' => 0],
        'dd' => ['dl' => 0, 'template' => 0],
        'figure' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'figcaption' => ['figure' => 0, 'template' => 0],
        'div' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'main' => ['a' => 0, 'address' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'form' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'a' => ['abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'em' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'strong' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'small' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        's' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'cite' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'q' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'dfn' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'abbr' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'data' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'time' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'code' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'var' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'samp' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'kbd' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'sub' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'sup' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'i' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'b' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'u' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'mark' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'ruby' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'rb' => ['ruby' => 0, 'template' => 0],
        'rt' => ['rtc' => 0, 'ruby' => 0, 'template' => 0],
        'rtc' => ['ruby' => 0, 'template' => 0],
        'rp' => ['ruby' => 0, 'template' => 0],
        'bdi' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'bdo' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'span' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'br' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'wbr' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'ins' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'del' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'img' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'iframe' => ['abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'embed' => ['abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'object' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'param' => ['object' => 0, 'template' => 0],
        'video' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0],
        'audio' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0],
        'source' => ['audio' => 0, 'template' => 0, 'video' => 0],
        'track' => ['audio' => 0, 'template' => 0, 'video' => 0],
        'map' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'area' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'b' => 0, 'blockquote' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'math' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'svg' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'table' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'caption' => ['table' => 0, 'template' => 0],
        'colgroup' => ['table' => 0, 'template' => 0],
        'col' => ['colgroup' => 0, 'template' => 0],
        'tbody' => ['table' => 0, 'template' => 0],
        'thead' => ['table' => 0, 'template' => 0],
        'tfoot' => ['table' => 0, 'template' => 0],
        'tr' => ['table' => 0, 'tbody' => 0, 'template' => 0, 'tfoot' => 0, 'thead' => 0],
        'th' => ['template' => 0, 'tr' => 0],
        'td' => ['template' => 0, 'tr' => 0],
        'form' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'label' => ['abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'input' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'button' => ['abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'select' => ['abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'datalist' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'optgroup' => ['select' => 0, 'template' => 0],
        'option' => ['datalist' => 0, 'optgroup' => 0, 'select' => 0, 'template' => 0],
        'textarea' => ['abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'keygen' => ['abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'output' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'progress' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'meter' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'fieldset' => ['a' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'blockquote' => 0, 'body' => 0, 'canvas' => 0, 'caption' => 0, 'dd' => 0, 'del' => 0, 'div' => 0, 'dt' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'header' => 0, 'ins' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'section' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'video' => 0],
        'legend' => ['fieldset' => 0, 'template' => 0],
        'script' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dl' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'head' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'ol' => 0, 'optgroup' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'select' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'table' => 0, 'tbody' => 0, 'td' => 0, 'template' => 0, 'tfoot' => 0, 'thead' => 0, 'th' => 0, 'time' => 0, 'tr' => 0, 'u' => 0, 'ul' => 0, 'var' => 0, 'video' => 0],
        'noscript' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'head' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'template' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'colgroup' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dl' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'head' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'ol' => 0, 'optgroup' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'select' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'table' => 0, 'tbody' => 0, 'td' => 0, 'template' => 0, 'tfoot' => 0, 'thead' => 0, 'th' => 0, 'time' => 0, 'tr' => 0, 'u' => 0, 'ul' => 0, 'var' => 0, 'video' => 0],
        'canvas' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'th' => 0, 'time' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
        'textnode' => ['a' => 0, 'abbr' => 0, 'address' => 0, 'article' => 0, 'aside' => 0, 'audio' => 0, 'b' => 0, 'blockquote' => 0, 'body' => 0, 'button' => 0, 'canvas' => 0, 'caption' => 0, 'cite' => 0, 'code' => 0, 'data' => 0, 'datalist' => 0, 'dd' => 0, 'del' => 0, 'dfn' => 0, 'div' => 0, 'dt' => 0, 'em' => 0, 'fieldset' => 0, 'figcaption' => 0, 'figure' => 0, 'footer' => 0, 'form' => 0, 'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0, 'header' => 0, 'i' => 0, 'iframe' => 0, 'ins' => 0, 'kbd' => 0, 'label' => 0, 'legend' => 0, 'li' => 0, 'main' => 0, 'map' => 0, 'mark' => 0, 'meter' => 0, 'nav' => 0, 'noscript' => 0, 'object' => 0, 'option' => 0, 'output' => 0, 'p' => 0, 'pre' => 0, 'progress' => 0, 'q' => 0, 'rb' => 0, 'rp' => 0, 'rt' => 0, 'rtc' => 0, 'ruby' => 0, 's' => 0, 'samp' => 0, 'script' => 0, 'section' => 0, 'small' => 0, 'span' => 0, 'strong' => 0, 'style' => 0, 'sub' => 0, 'sup' => 0, 'td' => 0, 'template' => 0, 'textarea' => 0, 'th' => 0, 'time' => 0, 'title' => 0, 'u' => 0, 'var' => 0, 'video' => 0],
    ];

    protected $always_indention_start_tags = [
        'html' => 0,
        'head' => 0, 'body' => 0,
        'header' => 0, 'footer' => 0,
        'base' => 0, 'meta' => 0, 'link' => 0, 'title' => 0,
        'article' => 0, 'aside' => 0, 'section' => 0,
        'table' => 0, 'caption' => 0, 'thead' => 0, 'tbody' => 0, 'tfoot' => 0, 'tr' => 0, 'th' => 0, 'td' => 0,
        'form' => 0, 'select' => 0,
        'ul' => 0, 'ol' => 0, 'li' => 0,
        'dl' => 0, 'dt' => 0, 'dd' => 0,
        'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0,
        'p' => 0,
        'hr' => 0,
        'optgroup' => 0, 'option' => 0,
        'script' => 0, 'noscript' => 0,
    ];
    protected $always_wrap_start_tags = [
        'html' => 0,
        'head' => 0, 'body' => 0,
        'header' => 0, 'footer' => 0,
        'meta' => 0, 'link' => 0,
        'form' => 0,
        'hr' => 0, 'br' => 0,
    ];
    protected $always_indention_end_tags = [
        'html' => 0,
        'head' => 0, 'body' => 0,
        'header' => 0, 'footer' => 0,
        'article' => 0, 'aside' => 0, 'section' => 0,
        'table' => 0, 'thead' => 0, 'tbody' => 0, 'tfoot' => 0, 'tr' => 0,
        'ul' => 0, 'ol' => 0, 'dl' => 0,
        'section' => 0,
    ];
    protected $always_wrap_end_tags = [
        'html' => 0,
        'head' => 0, 'body' => 0,
        'main' => 0,
        'header' => 0, 'footer' => 0,
        'table' => 0, 'caption' => 0, 'thead' => 0, 'tbody' => 0, 'tfoot' => 0, 'tr' => 0, 'th' => 0, 'td' => 0,
        'h1' => 0, 'h2' => 0, 'h3' => 0, 'h4' => 0, 'h5' => 0, 'h6' => 0,
        'optgroup' => 0, 'option' => 0,
        'ul' => 0,
    ];

    protected $entrust_indention_by_source = [
        'div' => 0, 'span' => 0,
        'main' => 0,
        'a' => 0,
        'label' => 0,
        'input' => 0, 'textarea' => 0,
        'script' => 0, 'noscript' => 0,
    ];
}
